# ============================================================
# Dictionnaire des phonèmes de référence — 80 classes YOLOv8
# Chaque clé correspond à un mot (par index)
# Chaque valeur est la liste des phonèmes ARPAbet de référence
# ============================================================

dataset = {
    "0":  {"word": "person",         "phonemes": ["p", "er", "s", "ah", "n"]},
    "1":  {"word": "bicycle",        "phonemes": ["b", "ay", "s", "ih", "k", "l"]},
    "2":  {"word": "car",            "phonemes": ["k", "aa", "r"]},
    "3":  {"word": "motorcycle",     "phonemes": ["m", "ow", "t", "er", "s", "ay", "k", "l"]},
    "4":  {"word": "airplane",       "phonemes": ["ey", "r", "p", "l", "ey", "n"]},
    "5":  {"word": "bus",            "phonemes": ["b", "ah", "s"]},
    "6":  {"word": "train",          "phonemes": ["t", "r", "ey", "n"]},
    "7":  {"word": "truck",          "phonemes": ["t", "r", "ah", "k"]},
    "8":  {"word": "boat",           "phonemes": ["b", "ow", "t"]},
    "9":  {"word": "traffic light",  "phonemes": ["t", "r", "ae", "f", "ih", "k", "l", "ay", "t"]},
    "10": {"word": "fire hydrant",   "phonemes": ["f", "ay", "r", "h", "ay", "d", "r", "ah", "n", "t"]},
    "11": {"word": "stop sign",      "phonemes": ["s", "t", "aa", "p", "s", "ay", "n"]},
    "12": {"word": "parking meter",  "phonemes": ["p", "aa", "r", "k", "ih", "ng", "m", "iy", "t", "er"]},
    "13": {"word": "bench",          "phonemes": ["b", "eh", "n", "ch"]},
    "14": {"word": "bird",           "phonemes": ["b", "er", "d"]},
    "15": {"word": "cat",            "phonemes": ["k", "ae", "t"]},
    "16": {"word": "dog",            "phonemes": ["d", "ao", "g"]},
    "17": {"word": "horse",          "phonemes": ["hh", "ao", "r", "s"]},
    "18": {"word": "sheep",          "phonemes": ["sh", "iy", "p"]},
    "19": {"word": "cow",            "phonemes": ["k", "aw"]},
    "20": {"word": "elephant",       "phonemes": ["eh", "l", "ah", "f", "ah", "n", "t"]},
    "21": {"word": "bear",           "phonemes": ["b", "eh", "r"]},
    "22": {"word": "zebra",          "phonemes": ["z", "iy", "b", "r", "ah"]},
    "23": {"word": "giraffe",        "phonemes": ["jh", "ih", "r", "ae", "f"]},
    "24": {"word": "backpack",       "phonemes": ["b", "ae", "k", "p", "ae", "k"]},
    "25": {"word": "umbrella",       "phonemes": ["ah", "m", "b", "r", "eh", "l", "ah"]},
    "26": {"word": "handbag",        "phonemes": ["hh", "ae", "n", "d", "b", "ae", "g"]},
    "27": {"word": "tie",            "phonemes": ["t", "ay"]},
    "28": {"word": "suitcase",       "phonemes": ["s", "uw", "t", "k", "ey", "s"]},
    "29": {"word": "frisbee",        "phonemes": ["f", "r", "ih", "z", "b", "iy"]},
    "30": {"word": "skis",           "phonemes": ["s", "k", "iy", "z"]},
    "31": {"word": "snowboard",      "phonemes": ["s", "n", "ow", "b", "ao", "r", "d"]},
    "32": {"word": "sports ball",    "phonemes": ["s", "p", "ao", "r", "t", "s", "b", "ao", "l"]},
    "33": {"word": "kite",           "phonemes": ["k", "ay", "t"]},
    "34": {"word": "baseball bat",   "phonemes": ["b", "ey", "s", "b", "ao", "l", "b", "ae", "t"]},
    "35": {"word": "baseball glove", "phonemes": ["b", "ey", "s", "b", "ao", "l", "g", "l", "ah", "v"]},
    "36": {"word": "skateboard",     "phonemes": ["s", "k", "ey", "t", "b", "ao", "r", "d"]},
    "37": {"word": "surfboard",      "phonemes": ["s", "er", "f", "b", "ao", "r", "d"]},
    "38": {"word": "tennis racket",  "phonemes": ["t", "eh", "n", "ih", "s", "r", "ae", "k", "ih", "t"]},
    "39": {"word": "bottle",         "phonemes": ["b", "aa", "t", "l"]},
    "40": {"word": "wine glass",     "phonemes": ["w", "ay", "n", "g", "l", "ae", "s"]},
    "41": {"word": "cup",            "phonemes": ["k", "ah", "p"]},
    "42": {"word": "fork",           "phonemes": ["f", "ao", "r", "k"]},
    "43": {"word": "knife",          "phonemes": ["n", "ay", "f"]},
    "44": {"word": "spoon",          "phonemes": ["s", "p", "uw", "n"]},
    "45": {"word": "bowl",           "phonemes": ["b", "ow", "l"]},
    "46": {"word": "banana",         "phonemes": ["b", "ah", "n", "ae", "n", "ah"]},
    "47": {"word": "apple",          "phonemes": ["ae", "p", "l"]},
    "48": {"word": "sandwich",       "phonemes": ["s", "ae", "n", "d", "w", "ih", "ch"]},
    "49": {"word": "orange",         "phonemes": ["ao", "r", "ah", "n", "jh"]},
    "50": {"word": "broccoli",       "phonemes": ["b", "r", "aa", "k", "ah", "l", "iy"]},
    "51": {"word": "carrot",         "phonemes": ["k", "eh", "r", "ah", "t"]},
    "52": {"word": "hot dog",        "phonemes": ["hh", "aa", "t", "d", "ao", "g"]},
    "53": {"word": "pizza",          "phonemes": ["p", "iy", "t", "s", "ah"]},
    "54": {"word": "donut",          "phonemes": ["d", "ow", "n", "ah", "t"]},
    "55": {"word": "cake",           "phonemes": ["k", "ey", "k"]},
    "56": {"word": "chair",          "phonemes": ["ch", "eh", "r"]},
    "57": {"word": "couch",          "phonemes": ["k", "aw", "ch"]},
    "58": {"word": "potted plant",   "phonemes": ["p", "aa", "t", "ih", "d", "p", "l", "ae", "n", "t"]},
    "59": {"word": "bed",            "phonemes": ["b", "eh", "d"]},
    "60": {"word": "dining table",   "phonemes": ["d", "ay", "n", "ih", "ng", "t", "ey", "b", "l"]},
    "61": {"word": "toilet",         "phonemes": ["t", "oy", "l", "ah", "t"]},
    "62": {"word": "tv",             "phonemes": ["t", "iy", "v", "iy"]},
    "63": {"word": "laptop",         "phonemes": ["l", "ae", "p", "t", "aa", "p"]},
    "64": {"word": "mouse",          "phonemes": ["m", "aw", "s"]},
    "65": {"word": "remote",         "phonemes": ["r", "ih", "m", "ow", "t"]},
    "66": {"word": "keyboard",       "phonemes": ["k", "iy", "b", "ao", "r", "d"]},
    "67": {"word": "cell phone",     "phonemes": ["s", "eh", "l", "f", "ow", "n"]},
    "68": {"word": "microwave",      "phonemes": ["m", "ay", "k", "r", "ow", "w", "ey", "v"]},
    "69": {"word": "oven",           "phonemes": ["ah", "v", "ah", "n"]},
    "70": {"word": "toaster",        "phonemes": ["t", "ow", "s", "t", "er"]},
    "71": {"word": "sink",           "phonemes": ["s", "ih", "ng", "k"]},
    "72": {"word": "refrigerator",   "phonemes": ["r", "ih", "f", "r", "ih", "jh", "er", "ey", "t", "er"]},
    "73": {"word": "book",           "phonemes": ["b", "uh", "k"]},
    "74": {"word": "clock",          "phonemes": ["k", "l", "aa", "k"]},
    "75": {"word": "vase",           "phonemes": ["v", "ey", "s"]},
    "76": {"word": "scissors",       "phonemes": ["s", "ih", "z", "er", "z"]},
    "77": {"word": "teddy bear",     "phonemes": ["t", "eh", "d", "iy", "b", "eh", "r"]},
    "78": {"word": "hair drier",     "phonemes": ["hh", "eh", "r", "d", "r", "ay", "er"]},
    "79": {"word": "toothbrush",     "phonemes": ["t", "uw", "th", "b", "r", "ah", "sh"]},
}

# Mapping nom de fichier audio → index du mot
filename_to_index = {entry["word"]: key for key, entry in dataset.items()}