// Les 80 classes COCO/YOLO reconnues par l'application.
//
// - `image` : vraie photo fournie et vérifiée (frontend/public/images/objects/),
//   utilisée en priorité pour un rendu fidèle (visage/objet bien visible, jamais rogné).
// - `emoji` : utilisé uniquement en toute petite vignette dans la galerie si besoin ;
//   `null` quand aucun emoji Unicode exact n'existe pour ce mot (vérifié manuellement).
export const WORDS = [
  { word: "person", fr: "Personne", emoji: "🧑", image: "/images/objects/person.png" },
  { word: "bicycle", fr: "Vélo", emoji: "🚲", image: "/images/objects/bicycle.jpg" },
  { word: "car", fr: "Voiture", emoji: "🚗", image: "/images/objects/car.jpg" },
  { word: "motorcycle", fr: "Moto", emoji: "🏍️", image: "/images/objects/motorcycle.jpg" },
  { word: "airplane", fr: "Avion", emoji: "✈️", image: "/images/objects/airplane.jpg" },
  { word: "bus", fr: "Bus", emoji: "🚌", image: "/images/objects/bus.jpg" },
  { word: "train", fr: "Train", emoji: "🚆", image: "/images/objects/train.jpg" },
  { word: "truck", fr: "Camion", emoji: "🚚", image: "/images/objects/truck.jpg" },
  { word: "boat", fr: "Bateau", emoji: "⛵", image: "/images/objects/boat.jpg" },
  { word: "traffic light", fr: "Feu de circulation", emoji: "🚦", image: "/images/objects/traffic_light.jpg" },
  { word: "fire hydrant", fr: "Bouche d'incendie", emoji: null, image: "/images/objects/fire_hydrant.jpg" },
  { word: "stop sign", fr: "Panneau stop", emoji: "🛑", image: "/images/objects/stop_sign.jpg" },
  { word: "parking meter", fr: "Parcmètre", emoji: null, image: "/images/objects/parking_meter.jpg" },
  { word: "bench", fr: "Banc", emoji: null, image: "/images/objects/bench.jpg" },
  { word: "bird", fr: "Oiseau", emoji: "🐦", image: "/images/objects/bird.jpg" },
  { word: "cat", fr: "Chat", emoji: "🐱", image: "/images/objects/cat.jpg" },
  { word: "dog", fr: "Chien", emoji: "🐶", image: "/images/objects/dog.jpg" },
  { word: "horse", fr: "Cheval", emoji: "🐴", image: "/images/objects/horse.jpg" },
  { word: "sheep", fr: "Mouton", emoji: "🐑", image: "/images/objects/sheep.jpg" },
  { word: "cow", fr: "Vache", emoji: "🐄", image: "/images/objects/cow.jpg" },
  { word: "elephant", fr: "Éléphant", emoji: "🐘", image: "/images/objects/elephant.jpg" },
  { word: "bear", fr: "Ours", emoji: "🐻", image: "/images/objects/bear.jpg" },
  { word: "zebra", fr: "Zèbre", emoji: "🦓", image: "/images/objects/zebra.jpg" },
  { word: "giraffe", fr: "Girafe", emoji: "🦒", image: "/images/objects/giraffe.jpg" },
  { word: "backpack", fr: "Sac à dos", emoji: "🎒", image: "/images/objects/backpack.jpg" },
  { word: "umbrella", fr: "Parapluie", emoji: "☂️", image: "/images/objects/umbrella.jpg" },
  { word: "handbag", fr: "Sac à main", emoji: "👜", image: "/images/objects/handbag.jpg" },
  { word: "tie", fr: "Cravate", emoji: "👔", image: "/images/objects/tie.jpg" },
  { word: "suitcase", fr: "Valise", emoji: "🧳", image: "/images/objects/suitcase.jpg" },
  { word: "frisbee", fr: "Frisbee", emoji: "🥏", image: "/images/objects/frisbee.jpg" },
  { word: "skis", fr: "Skis", emoji: "🎿", image: "/images/objects/skis.jpg" },
  { word: "snowboard", fr: "Snowboard", emoji: "🏂", image: "/images/objects/snowboard.jpg" },
  { word: "sports ball", fr: "Ballon de sport", emoji: "⚽", image: "/images/objects/sports_ball.jpg" },
  { word: "kite", fr: "Cerf-volant", emoji: "🪁", image: "/images/objects/kite.jpg" },
  { word: "baseball bat", fr: "Batte de baseball", emoji: null, image: "/images/objects/baseball_bat.jpg" },
  { word: "baseball glove", fr: "Gant de baseball", emoji: null, image: "/images/objects/baseball_glove.jpg" },
  { word: "skateboard", fr: "Skateboard", emoji: "🛹", image: "/images/objects/skateboard.jpg" },
  { word: "surfboard", fr: "Planche de surf", emoji: "🏄", image: "/images/objects/surfboard.jpg" },
  { word: "tennis racket", fr: "Raquette de tennis", emoji: null, image: "/images/objects/tennis_racket.jpg" },
  { word: "bottle", fr: "Bouteille", emoji: null, image: "/images/objects/bottle.jpg" },
  { word: "wine glass", fr: "Verre à vin", emoji: "🍷", image: "/images/objects/wine_glass.jpg" },
  { word: "cup", fr: "Tasse", emoji: "☕", image: "/images/objects/cup.jpg" },
  { word: "fork", fr: "Fourchette", emoji: null, image: "/images/objects/fork.jpg" },
  { word: "knife", fr: "Couteau", emoji: "🔪", image: "/images/objects/knife.jpg" },
  { word: "spoon", fr: "Cuillère", emoji: "🥄", image: "/images/objects/spoon.jpg" },
  { word: "bowl", fr: "Bol", emoji: "🥣", image: "/images/objects/bowl.jpg" },
  { word: "banana", fr: "Banane", emoji: "🍌", image: "/images/objects/banana.jpg" },
  { word: "apple", fr: "Pomme", emoji: "🍎", image: "/images/objects/apple.jpg" },
  { word: "sandwich", fr: "Sandwich", emoji: "🥪", image: "/images/objects/sandwich.jpg" },
  { word: "orange", fr: "Orange", emoji: "🍊", image: "/images/objects/orange.jpg" },
  { word: "broccoli", fr: "Brocoli", emoji: "🥦", image: "/images/objects/broccoli.jpg" },
  { word: "carrot", fr: "Carotte", emoji: "🥕", image: "/images/objects/carrot.jpg" },
  { word: "hot dog", fr: "Hot-dog", emoji: "🌭", image: "/images/objects/hot_dog.jpg" },
  { word: "pizza", fr: "Pizza", emoji: "🍕", image: "/images/objects/pizza.jpg" },
  { word: "donut", fr: "Beignet", emoji: "🍩", image: "/images/objects/donut.jpg" },
  { word: "cake", fr: "Gâteau", emoji: "🎂", image: "/images/objects/cake.jpg" },
  { word: "chair", fr: "Chaise", emoji: "🪑", image: "/images/objects/chair.jpg" },
  { word: "couch", fr: "Canapé", emoji: "🛋️", image: "/images/objects/couch.jpg" },
  { word: "potted plant", fr: "Plante en pot", emoji: "🪴", image: "/images/objects/potted_plant.jpg" },
  { word: "bed", fr: "Lit", emoji: "🛏️", image: "/images/objects/bed.jpg" },
  { word: "dining table", fr: "Table à manger", emoji: null, image: "/images/objects/dining_table.jpg" },
  { word: "toilet", fr: "Toilettes", emoji: "🚽", image: "/images/objects/toilet.jpg" },
  { word: "tv", fr: "Télévision", emoji: "📺", image: "/images/objects/tv.jpg" },
  { word: "laptop", fr: "Ordinateur portable", emoji: "💻", image: "/images/objects/laptop.jpg" },
  { word: "mouse", fr: "Souris (ordinateur)", emoji: "🖱️", image: "/images/objects/mouse.jpg" },
  { word: "remote", fr: "Télécommande", emoji: null, image: "/images/objects/remote.jpg" },
  { word: "keyboard", fr: "Clavier", emoji: "⌨️", image: "/images/objects/keyboard.jpg" },
  { word: "cell phone", fr: "Téléphone portable", emoji: "📱", image: "/images/objects/cell_phone.jpg" },
  { word: "microwave", fr: "Micro-ondes", emoji: null, image: "/images/objects/microwave.jpg" },
  { word: "oven", fr: "Four", emoji: null, image: "/images/objects/oven.jpg" },
  { word: "toaster", fr: "Grille-pain", emoji: null, image: "/images/objects/toaster.jpg" },
  { word: "sink", fr: "Évier", emoji: "🚰", image: "/images/objects/sink.jpg" },
  { word: "refrigerator", fr: "Réfrigérateur", emoji: null, image: "/images/objects/refrigerator.jpg" },
  { word: "book", fr: "Livre", emoji: "📚", image: "/images/objects/book.jpg" },
  { word: "clock", fr: "Horloge", emoji: "🕐", image: "/images/objects/clock.jpg" },
  { word: "vase", fr: "Vase", emoji: "🏺", image: "/images/objects/vase.jpg" },
  { word: "scissors", fr: "Ciseaux", emoji: "✂️", image: "/images/objects/scissors.jpg" },
  { word: "teddy bear", fr: "Ours en peluche", emoji: "🧸", image: "/images/objects/teddy_bear.jpg" },
  { word: "hair drier", fr: "Sèche-cheveux", emoji: null, image: "/images/objects/hair_drier.jpg" },
  { word: "toothbrush", fr: "Brosse à dents", emoji: "🪥", image: "/images/objects/toothbrush.jpg" },
];

export const YOLO_CLASSES = WORDS.map((w) => w.word);

export function getWordInfo(word) {
  return WORDS.find((w) => w.word === word) || { word, fr: word, emoji: null, image: null };
}
